In [1]:
f(x) = x^3 - x

f (generic function with 1 method)

In [2]:
f(3)

24

In [3]:
@code_llvm debuginfo = :none f(3)

define i64 @julia_f_897(i64 signext %0) #0 {
top:
  %1 = mul i64 %0, %0
  %2 = mul i64 %1, %0
  %3 = sub i64 %2, %0
  ret i64 %3
}


In [4]:
@code_llvm debuginfo = :none f(1.5)

define double @julia_f_922(double %0) #0 {
top:
  %1 = fmul double %0, %0
  %2 = fmul double %1, %0
  %3 = fsub double %2, %0
  ret double %3
}


In [7]:
using Plots

plot(f, xlims=(-2, 2), ylims = (-2, 2), framestyle = :origin, aspect_ratio = 1, label = "y = x³ - x")

In [8]:
A = rand(5,5)

5×5 Matrix{Float64}:
 0.31861   0.405681  0.931205  0.285062  0.249251
 0.36356   0.922227  0.447478  0.740319  0.774522
 0.243903  0.439802  0.637628  0.84524   0.583584
 0.451579  0.809628  0.279966  0.757493  0.973794
 0.770745  0.263092  0.02898   0.642441  0.634272

In [9]:
f(A)

5×5 Matrix{Float64}:
 2.41758  3.16219  1.56602  3.87632  3.94668
 3.90665  4.48149  3.33127  5.38178  5.4934
 3.3968   4.126    2.52286  4.36163  4.75685
 3.76779  4.48683  3.50693  5.22741  5.15485
 2.01374  3.27277  2.66821  3.43276  3.44477

In [10]:
b = [-2, -1, 0, 1, 2]

5-element Vector{Int64}:
 -2
 -1
  0
  1
  2

In [11]:
f(b)

LoadError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)

Closest candidates are:
  ^(::Float16, ::Integer)
   @ Base math.jl:1283
  ^(::Regex, ::Integer)
   @ Base regex.jl:863
  ^(::Float32, ::Integer)
   @ Base math.jl:1277
  ...


In [12]:
map(f, b)

5-element Vector{Int64}:
 -6
  0
  0
  0
  6

In [13]:
f.(b)

5-element Vector{Int64}:
 -6
  0
  0
  0
  6

In [14]:
using LinearAlgebra

A \ b

5-element Vector{Float64}:
 -0.25635265427953985
 -5.104170583125122
 -1.3275678152545365
 -0.5472056605021854
  6.196816407472394

In [19]:
Q, R = qr(A)
(inv(factorize(R))Q') * b

5-element Vector{Float64}:
 -0.2563526542795431
 -5.104170583125128
 -1.3275678152545347
 -0.5472056605021893
  6.196816407472404

In [20]:
U, S, V = svd(A)
V * Diagonal(1 ./ S) * U' * b

5-element Vector{Float64}:
 -0.2563526542795447
 -5.104170583125131
 -1.3275678152545363
 -0.5472056605021862
  6.196816407472406

In [21]:
using SparseArrays

rows = [1,3,4,2,1,3,1,4,1,5]
cols = [1,1,1,2,3,3,4,4,5,5]
vals = [1,-2,-4,5,-3,-1,-2,1,7,-1]

A = sparse(rows, cols, vals, 5, 5)

5×5 SparseMatrixCSC{Int64, Int64} with 10 stored entries:
  1  ⋅  -3  -2   7
  ⋅  5   ⋅   ⋅   ⋅
 -2  ⋅  -1   ⋅   ⋅
 -4  ⋅   ⋅   1   ⋅
  ⋅  ⋅   ⋅   ⋅  -1

In [22]:
b = collect(1:5)

A * b

5-element Vector{Int64}:
 19
 10
 -5
  0
 -5

In [23]:
vcat(ones(5)', rand(4,5))

5×5 Matrix{Float64}:
 1.0        1.0        1.0       1.0       1.0
 0.0782003  0.0849043  0.527541  0.724058  0.746632
 0.484388   0.116351   0.841016  0.382058  0.322394
 0.32082    0.161081   0.589138  0.846281  0.582013
 0.28158    0.367238   0.748825  0.523316  0.44398

In [24]:
using Random

function generate_data( rng, β; num_samples = 100, noise = 0.01)

    num_features = length(β) - 1
    x = vcat(ones(num_samples)', randn(rng, (num_features, num_samples)))  # création des variables explicatives
    y =  x' * β .+ noise .* randn(rng, num_samples)

    return x, y

end

rng = Xoshiro(1234)

weights = [0.1, 0.2, 0.3, 0.4, 0.5 ]
bias = 1.0
β = [bias, weights...]

6-element Vector{Float64}:
 1.0
 0.1
 0.2
 0.3
 0.4
 0.5

In [25]:
x, y =  generate_data( rng, β)

([1.0 1.0 … 1.0 1.0; 0.9706563288552144 -1.445177115286233 … 0.6785478622508077 -0.2702750330391049; … ; -0.03280312924463938 0.759804020007466 … 0.4207068461244445 -1.2139401711703544; -0.6007922233555612 -0.8814369061964817 … -0.31934708892587327 1.0914985820684815], [0.857367129020362, 1.7054712475117926, 2.051575125931088, 0.07098096740491859, 0.41553055093608615, 1.6969921297327404, 0.4297595204119519, -0.12530952219770528, 0.2788086540031869, 1.822435013919742  …  1.538820217823834, 1.6959881951955973, 0.7062436075061378, 0.7527966528477439, 0.35965658336778444, -0.012267018858788892, 0.19454649272747426, 1.091104244320309, 0.855704318606509, 1.2268078852377329])

In [33]:

function linear_regression( x, y, β ; learning_rate = 0.01, iterations = 1000)
        
    num_features, num_samples  = size(x)
    
    for i in 1:iterations
        
        y_pred =  x' * β
        dβ = x * ( y_pred .- y ) ./ num_samples
        β .-= learning_rate .* dβ
        
    end
    
    return β     
end

β = ones(size(x,1))

w  = linear_regression( x, y, β)

6-element Vector{Float64}:
 1.0005294314119706
 0.10015509306034773
 0.20123561883647267
 0.29723226274216186
 0.3979459932379165
 0.4978432045167676

In [35]:
β = ones(Float32, size(x,1))
linear_regression( Float32.(x), Float32.(y), β)

6-element Vector{Float32}:
 1.0005294
 0.10015513
 0.20123564
 0.29723227
 0.39794597
 0.49784324

In [38]:
using CUDA

β = CUDA.ones(size(x,1))
linear_regression(cu(x), cu(y), β)

6-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 1.0005294
 0.10015514
 0.20123562
 0.29723227
 0.39794597
 0.49784324

In [41]:
weights = rand(100)
bias = 1.0
β = [bias, weights...]
x, y =  generate_data( rng, β, num_samples=100_000)

([1.0 1.0 … 1.0 1.0; -0.30833358989214027 1.125113065495088 … 0.6600793319099784 0.7071796852620895; … ; 1.4387649408348513 -0.05584818865532804 … -0.5297706927492861 0.08609293782140201; 0.9452286146307545 1.7577108475733658 … 0.939621612382447 0.9480153495810533], [0.2158834692680112, 0.8826899182403306, -5.745853927697969, 1.2991502254977525, 7.0036619515202405, -0.3914962990603192, 1.3370804766576336, 1.070594851646446, -0.5812122446289688, 5.9333051555747005  …  -5.58566918180413, 0.6747625438963386, -2.629359434027558, 1.7054620704038816, -3.6219909455885437, -8.57490014275458, -8.068133365084407, -2.94432324836263, -2.672558999301055, 5.069663215552615])

In [42]:
@time linear_regression( x, y, β)

  5.859550 seconds (6.02 k allocations: 1.492 GiB, 3.15% gc time)


101-element Vector{Float64}:
 1.0000372589757331
 0.8987280568185765
 0.5223563804068403
 0.2837492506548321
 0.005832835404175131
 0.6257740827989775
 0.955641692249159
 0.1654664532833403
 0.39410323763772254
 0.5100995929363635
 0.18379253944388974
 0.895464972152817
 0.34731397097071093
 ⋮
 0.5010492235033828
 0.24947530296829323
 0.37691297901778614
 0.5923716644490593
 0.233181655390196
 0.5463006751429789
 0.7589882653255786
 0.7945507171109977
 0.04767317704037133
 0.14656566062553733
 0.724466241790347
 0.4282636712217966

In [43]:
β = CUDA.ones(size(x,1))
CUDA.@time linear_regression(cu(x), cu(y), β)

  0.216315 seconds (101.42 k CPU allocations: 44.434 MiB, 4.38% gc time) (4.00 k GPU allocations: 802.620 MiB, 6.15% memmgmt time)


101-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 1.0000436
 0.8987305
 0.52238905
 0.28378525
 0.0058775065
 0.6257856
 0.9556502
 0.16550796
 0.3941281
 0.51010275
 0.18382934
 0.89546114
 0.34734514
 ⋮
 0.50107807
 0.2495273
 0.37693718
 0.59239376
 0.23321615
 0.546349
 0.75901055
 0.79455763
 0.047707077
 0.14660569
 0.72447324
 0.4282955

In [44]:
struct LinearRegression{T}

   learning_rate :: T
   iterations :: Int 
   β :: Vector{T}
    
   function LinearRegression( x :: Matrix{T}, y :: Vector{T}; learning_rate = 0.01, iterations = 1000) where T
        
        num_features, num_samples  = size(x)
        β = Vector{T}(undef, num_features)
        linear_regression(x, y, β; learning_rate = learning_rate, iterations = iterations)
        
        new{T}( learning_rate, iterations, β)
        
    end
        
end


model = LinearRegression(x, y)

model.β

101-element Vector{Float64}:
 0.9999967393865732
 0.8986758280848707
 0.5223264186320108
 0.28373227074515583
 0.005840680251106454
 0.625752156041415
 0.9555784413956435
 0.16546367664123368
 0.39408708886581456
 0.5100797427279238
 0.1837806132275803
 0.895425479249716
 0.34729921915481493
 ⋮
 0.5010212406650502
 0.24945266936622507
 0.37689538494409897
 0.5923492117280896
 0.23316980809288845
 0.5462788373888692
 0.7589420324699844
 0.7945042821730981
 0.04767596192972461
 0.14656779196131003
 0.7244325478253487
 0.42823621760798924

In [47]:
predict(model :: LinearRegression, x) = x' * model.β

function Base.show(io :: IO, model :: LinearRegression) 
    println(io, "Linear Regression")
    println(io, "=================")
    println(io, "β : $(round.(model.β, digits=3))")
end

model

Linear Regression
β : [1.0, 0.899, 0.522, 0.284, 0.006, 0.626, 0.956, 0.165, 0.394, 0.51, 0.184, 0.895, 0.347, 0.348, 0.331, 0.14, 0.905, 0.873, 0.588, 0.332, 0.709, 0.019, 0.349, 0.464, 0.807, 0.074, 0.176, 0.218, 0.013, 0.322, 0.892, 0.507, 0.921, 0.36, 0.006, 0.196, 0.148, 0.272, 0.006, 0.003, 0.064, 0.506, 0.124, 0.155, 0.244, 0.782, 0.485, 0.688, 0.616, 0.107, 0.359, 0.365, 0.437, 0.624, 0.075, 0.146, 0.644, 0.71, 0.517, 0.025, 0.796, 0.346, 0.792, 0.019, 0.884, 0.081, 0.195, 0.703, 0.499, 0.912, 0.519, 0.116, 0.054, 0.348, 0.158, 0.959, 0.08, 0.978, 0.534, 0.879, 0.835, 0.172, 0.211, 0.221, 0.659, 0.802, 0.132, 0.227, 0.276, 0.501, 0.249, 0.377, 0.592, 0.233, 0.546, 0.759, 0.795, 0.048, 0.147, 0.724, 0.428]


In [48]:
model_f0 = LinearRegression(Float32.(x), Float32.(y))

Linear Regression
β : Float32[1.0, 0.899, 0.522, 0.284, 0.006, 0.626, 0.956, 0.165, 0.394, 0.51, 0.184, 0.895, 0.347, 0.348, 0.331, 0.14, 0.905, 0.873, 0.588, 0.332, 0.709, 0.019, 0.349, 0.464, 0.807, 0.074, 0.176, 0.218, 0.013, 0.322, 0.892, 0.507, 0.921, 0.36, 0.006, 0.196, 0.148, 0.272, 0.006, 0.003, 0.064, 0.506, 0.124, 0.155, 0.244, 0.782, 0.485, 0.688, 0.616, 0.107, 0.359, 0.365, 0.437, 0.624, 0.075, 0.146, 0.644, 0.71, 0.517, 0.025, 0.796, 0.346, 0.792, 0.019, 0.884, 0.081, 0.195, 0.703, 0.499, 0.912, 0.519, 0.116, 0.054, 0.348, 0.158, 0.959, 0.08, 0.978, 0.534, 0.879, 0.835, 0.172, 0.211, 0.221, 0.659, 0.802, 0.132, 0.227, 0.276, 0.501, 0.249, 0.377, 0.592, 0.233, 0.546, 0.759, 0.795, 0.048, 0.147, 0.724, 0.428]


In [49]:
model_f0.β

101-element Vector{Float32}:
 0.9999967
 0.89867586
 0.52232635
 0.28373227
 0.0058406997
 0.62575203
 0.9555785
 0.16546361
 0.3940871
 0.5100797
 0.1837806
 0.89542544
 0.34729916
 ⋮
 0.50102127
 0.2494526
 0.37689537
 0.5923491
 0.2331698
 0.54627883
 0.75894207
 0.79450434
 0.047675937
 0.14656745
 0.7244326
 0.4282362

In [50]:
model_gpu = LinearRegression(cu(x), cu(y))

LoadError: MethodError: no method matching LinearRegression(::CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, ::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer})